# 1) Numpy Arrays

## Array Basics

In [0]:
# 1D array

In [0]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [0]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [0]:
# 2D array

In [0]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy arrays using built in methods

In [0]:
import numpy as np

In [0]:
# 1) arange

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [0]:
# 2) zeros

In [16]:
np.zeros(3) # 1D array

array([0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# 3) ones

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
# 4) linspace

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [0]:
# 5) eye

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
# 6) arrays of random numbers (uniform distribution between 0 to 1)

In [27]:
np.random.rand(5)

array([0.21337924, 0.34351358, 0.60283276, 0.52600634, 0.87052328])

In [28]:
np.random.rand(4,4)

array([[0.84944478, 0.30155366, 0.78371239, 0.95365113],
       [0.9372001 , 0.97289715, 0.08049969, 0.24854353],
       [0.95982582, 0.75696152, 0.96834184, 0.9890999 ],
       [0.83014269, 0.86002864, 0.89380842, 0.18826982]])

In [0]:
# 7) Standard normal distribution or gaussion distribution

In [30]:
np.random.randn(4) # 1D array

array([ 0.38945605,  0.5601142 , -0.48206501,  1.3249432 ])

In [31]:
np.random.randn(4,5)

array([[-0.19610847, -0.91430814, -0.4159029 , -0.19877355, -0.74870738],
       [-0.13012639,  0.08375204, -1.77764776, -0.77925534, -0.25954449],
       [-1.60265109,  0.26938012, -1.30289883, -0.33655464, -0.94120079],
       [-1.13508572, -1.20525569, -0.48537928, -0.60789416,  0.16042516]])

In [0]:
# 8) randint

In [33]:
np.random.randint(0,100)

71

In [34]:
np.random.randint(0,100,10)

array([75, 88, 72, 27, 66, 71,  6, 43,  1, 47])

## Useful attributes and methods

In [0]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
# reshape method

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.reshape(5,10)

ValueError: ignored

In [0]:
# 2) max, min

In [0]:
ran_arr = np.random.randint(0,50,10)

In [43]:
ran_arr

array([39, 21, 30,  0, 13, 27,  2,  3, 47,  6])

In [44]:
ran_arr.max()

47

In [45]:
ran_arr.min()

0

In [46]:
ran_arr.argmax()

8

In [47]:
ran_arr.argmin()

3

In [0]:
# 3) shape

In [49]:
arr.shape

(25,)

In [0]:
b = arr.reshape(5,5)

In [51]:
b.shape

(5, 5)

In [0]:
# 4) dtype

In [53]:
arr.dtype

dtype('int64')

# 2) Numpy Indexing and Selection

## Indexing and Selection Basics

In [0]:
import numpy as np

In [0]:
arr = np.arange(10,21)

In [56]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
arr[5]

15

In [58]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [59]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

## broadcasting the values

In [61]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
arr[0:5] = 100

In [63]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [0]:
arr = np.arange(10,21)

In [65]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
slice_arr = arr[0:6]

In [67]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [0]:
slice_arr[:] = 99

In [69]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [70]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [0]:
arr_cp = arr.copy()

In [72]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [0]:
arr[:] = 100

In [74]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [75]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [0]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_2 = arr[0:5]

In [79]:
slice_2

array([0, 1, 2, 3, 4])

In [0]:
slice_2[:] = 100

In [81]:
slice_2

array([100, 100, 100, 100, 100])

In [82]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr_cp2 = arr.copy()

In [0]:
arr_cp2[:] = 200

In [85]:
arr_cp2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [86]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array(Matrix)

In [0]:
import numpy as np

In [0]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [89]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [90]:
arr_2d[0,0]

5

In [91]:
arr_2d[1,0]

20

In [92]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

## conditional selection

In [0]:
arr = np.arange(0,11)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [0]:
b = arr > 5

In [97]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [98]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [99]:
arr[arr < 8]

array([0, 1, 2, 3, 4, 5, 6, 7])

# 3) Numpy Operations

In [0]:
import numpy as np

In [0]:
# array with array

In [102]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [103]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [104]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
# array with sclar

In [108]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [109]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [110]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [111]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [112]:
1/0

ZeroDivisionError: ignored

In [113]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [114]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [0]:
# universal array functions

In [116]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [117]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [118]:
np.max(arr)

10

In [119]:
np.min(arr)

0

In [120]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [121]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])